@MediaStore_backend_HostAddress = http://localhost:5298

GET {{MediaStore_backend_HostAddress}}/mediastorepromos/
Accept: application/json

###

GET {{MediaStore_backend_HostAddress}}/mediastoreproduct/laptops
Accept: application/json

###

GET {{MediaStore_backend_HostAddress}}/mediastoreproduct/smartphones/3
Accept: application/json

###

GET {{MediaStore_backend_HostAddress}}/mediastoreproduct/popular
Accept: application/json

###
